### ISSUE TITLE
File Support

### ISSUE THREAD

**Issue by jaikishantulswani** [resyncgg/armada#3]
@d0nutptr It would be good if it have a flag to provide file having list of domains and ips both to scan.

**Comment by d0nutptr** [comment]
Hello! Thanks for the issue :) I've updated Armada to 1.1.1 which now supports passing targets via a file. Armada still does not support domains, but may make it into the next major set of updates. I'll close this issue since the primary component was the target file and we already have #2 which tracks domain resolution.

You can update armada by 

```
cargo install armada
```

And don't forget to give the binary `CAP_NET_RAW` if this is how you choose to use armada.

```
sudo setcap 'cap_net_raw+ep' $(which armada)
```

## Supported methods to supply targets

1. `--targets` (`-t`)
```
armada -t 1.1.1.1 -p 80,443
```
   
2. `--target_file`
```
armada --target_file ips_and_cidrs.txt -p 80,443
```
    
3. stdin
```
cat ips_and_cidrs.txt | armada -p 80,443
```
